### ISSUE TITLE
No compatible binary build

### ISSUE THREAD

**Issue by jaredtmartin** [markoshust/meteor-radium#5]
When uploading to meteor.com, I'm getting: "No compatible binary build found for this package. Contact the package author and ask them to publish it for your platform." Any idea what is causing this error?  I tried meteor update to make sure everything up-to-date.

**Comment by markshust** [comment]
Let me check this out, I was getting this error before when building the package. There seems to be something funky going on with creating packages with npm's for react plugins.

**Comment by markshust** [comment]
@jaredtmartin what operating system are you on? this is related to meteor's binary build process with npm's, and is platform-specific.

**Comment by jaredtmartin** [comment]
Mac el capitán

**Comment by adrianmcli** [comment]
@markoshust I am also having this problem. Any luck finding a solution?

**Comment by jaredtmartin** [comment]
I just made my own package. I'll publish it now. 

I just published it. jaredmartin:radium.  It might take a minute for it to appear. I just couldn't wait any longer to upload updates.

**Comment by markshust** [comment]
Hi @jaredtmartin  -- I think you missed my commit about 30 minutes ago :)

Radium, or something in Radium, is considered to contain a binary NPM. Binary NPM's need to be published with Build Machines (https://github.com/meteor/meteor/wiki/Build-Machines) -- these are slightly more complex than standard Meteor NPM container packages. 

I just pushed out an update and potential fix https://github.com/markoshust/meteor-radium/commit/424d800096533e2578db6f041a2d386dae77564c

Now, I did go forward and publish the binary NPM versions. The binaries successfully compiled for `os.osx.x86_64` and `os.linux.x86_64`. Meteor refused to publish packages for `os.linux.x86_32` and `os.windows.x86_32`, complaining that it cannot override an existing build. I have documented my full process and all commands, so if there is a bug in the Meteor build process, I'm ready to file a ticket with this.

Can you please test out the new version `markoshust:radium@0.14.3`, and let me know if it works correctly now?

**Comment by hyperh** [comment]
I have issues with the new version.

```
[[[[[ ~/web-dev/Meteor/adrian-test/mealtube ]]]]]

=> Started proxy.                             
=> Started MongoDB.                           

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Cannot find module 'externalify' from '/Users/hl/web-dev/Meteor/adrian-test/mealtube'
  at /Users/hl/.meteor/packages/cosmos_browserify/.0.8.3.1jl1ity++os+web.browser+web.cordova/plugin.CosmosBrowserify.os/npm/CosmosBrowserify/node_modules/browserify/node_modules/resolve/lib/async.js:46:17
  at process (/Users/hl/.meteor/packages/cosmos_browserify/.0.8.3.1jl1ity++os+web.browser+web.cordova/plugin.CosmosBrowserify.os/npm/CosmosBrowserify/node_modules/browserify/node_modules/resolve/lib/async.js:173:43)
  at ondir (/Users/hl/.meteor/packages/cosmos_browserify/.0.8.3.1jl1ity++os+web.browser+web.cordova/plugin.CosmosBrowserify.os/npm/CosmosBrowserify/node_modules/browserify/node_modules/resolve/lib/async.js:188:17)
  at load (/Users/hl/.meteor/packages/cosmos_browserify/.0.8.3.1jl1ity++os+web.browser+web.cordova/plugin.CosmosBrowserify.os/npm/CosmosBrowserify/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
  at onex (/Users/hl/.meteor/packages/cosmos_browserify/.0.8.3.1jl1ity++os+web.browser+web.cordova/plugin.CosmosBrowserify.os/npm/CosmosBrowserify/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
  at /Users/hl/.meteor/packages/cosmos_browserify/.0.8.3.1jl1ity++os+web.browser+web.cordova/plugin.CosmosBrowserify.os/npm/CosmosBrowserify/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
  at Object.oncomplete (fs.js:108:15)
```

**Comment by markshust** [comment]
@hyperh can you try removing `.meteor/local/plugin-cache/` and try again? perhaps an old version is cached. also, what operating system are you on?

**Comment by hyperh** [comment]
OSX El Capitan 10.11.1

Tried doing the remove `.meteor/local/plugin-cache/` didn't work.

**Comment by adrianmcli** [comment]
@markoshust The new version seems to work for me and I'm on the same OS version. That being said, I did get that same error once. I just ran it again and it worked fine.

**Comment by markshust** [comment]
@adrianmc glad to hear it worked

@hyperh is it possible this is caused by another package? can you do `meteor remove markoshust:radium` and see if you still receive that error?

**Comment by markshust** [comment]
I'm able to replicate. Looking at it.

**Comment by hyperh** [comment]
Tried removing the package, I am able to successfully build the project now.

**Comment by markshust** [comment]
@hyperh I'm having a hard time figuring out what is going on here. I'm able to replicate the issue. However, if I remove the package, create a new `packages` folder in a meteor poject, and clone this repo out to `packages/radium`, then add `markoshust:radium`, everything runs ok.

anyone have any clues? this is leading me to believe something funky is going on in meteor's publish/build process.

**Comment by hyperh** [comment]
Looks like that worked! Not sure what's going on really though haha.

**Comment by markshust** [comment]
@adrianmc how did you get this to work?

i tried to create a new meteor project:

`meteor create meteortest`

then add this package

`meteor add markoshust:radium`

and I'm receiving the `externalify` error.

**Comment by adrianmcli** [comment]
@markoshust

I really don't know. I was playing with Browserify before, but I was sure I removed it before the whole new version thing came out.

To update to your latest version, I removed and added back your package. I encountered the same error you guys had and then it went away. Quite strange. But maybe I did something else in the process? I'm not sure.

Sorry I can't be of more help.

**Comment by jaredtmartin** [comment]
Well, my package was working, and now when I want to redeploy it broke. :-/
So I tried your package again and I got the externally error.

**Comment by markshust** [comment]
Looks like issue/bug is in Meteor. See referenced ticket above. I'll keep this ticket open until the Meteor bug is resolved and can fix this package.

**Comment by jaredtmartin** [comment]
Ok, Thanks. For now, I just removed radium from my project.

**Comment by elidoran** [comment]
First, what I see in the error message is cosmos:browserify is looking in the root of the app and not finding the modules there. You're using the packages as a **published package**, so, it should be looking here: _~/.meteor/packages/markoshust_radium/0.14.3/npm/_

That means it's a bug in cosmos:browserify.

You're publishing to an arch. I haven't ever done that, and, I didn't test for it. So, a line in the plugin searches the isobuilds to find where the npm modules are located. What I did is find it in the _os_ build, but, it's in _os.osx..._ build. 

What I've done is changed the code to look for the _npmModulesPath_ property instead of trying to get it from the _os_ arch. This fixes the problem with your package.

I published the fix into versions 0.8.4+.

**Comment by markshust** [comment]
Ok, I just published `markoshust:radium@0.15.3` for the archs. Thanks @elidoran, `0.8.4` seems to have fixed this issue.

I did also finally manage to do a quick test with this radium package using `meteor deploy`, and it finally worked! This ticket should be resolved.

For my future reference, I only managed to `publish-for-arch` for the platforms:
`meteor admin get-machine os.osx.x86_64`
`meteor admin get-machine os.linux.x86_64`

I received errors when running for linux 32-bit:

```
Marks-MacBook-Air:meteor-radium markshust$ meteor admin get-machine os.linux.x86_32
Linux ip-172-31-34-93 2.6.32-356-ec2 #69-Ubuntu SMP Mon Aug 26 15:37:01 UTC 2013 i686 GNU/Linux
Ubuntu 10.04.4 LTS

Welcome to Ubuntu!
 * Documentation:  https://help.ubuntu.com/

  System information as of Wed Nov 18 14:04:37 UTC 2015

  System load:  0.0               Processes:           61
  Usage of /:   19.8% of 9.84GB   Users logged in:     0
  Memory usage: 5%                IP address for eth0: 172.31.34.93
  Swap usage:   0%

  Graph this data and manage this system at:
    https://landscape.canonical.com/

  Get cloud support with Ubuntu Advantage Cloud Guest:
    http://www.ubuntu.com/business/services/cloud
---------------------------------------------------------------------
At the moment, only the core of the system is installed. To tune the 
system to your needs, you can choose to install one or more          
predefined collections of software by running the following          
command:                                                             

   sudo tasksel --section server                                     
---------------------------------------------------------------------

0 packages can be updated.
0 updates are security updates.

New release 'precise' available.
Run 'do-release-upgrade' to upgrade to it.

A newer build of the Ubuntu lucid server image is available.
It is named 'release' and has build serial '20150427'.
*** System restart required ***

The programs included with the Ubuntu system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Ubuntu comes with ABSOLUTELY NO WARRANTY, to the extent permitted by
applicable law.

meteor@ip-172-31-34-93:~$ meteor publish-for-arch markoshust:radium@0.15.3
markoshust:radium: updating npm dependencies -- externalify, radium...

Some package versions changed since this package was published!

babel-compiler      added, version 5.8.24_1   
base64              added, version 1.0.4
caching-compiler    added, version 1.0.0
check               added, version 1.1.0
coffeescript        added, version 1.0.11
ecmascript          added, version 0.1.6
ecmascript-runtime  added, version 0.2.6
ejson               added, version 1.0.7
markoshust:radium   added, version 0.15.3
promise             added, version 0.5.1
random              added, version 1.0.5
react-runtime-dev   added, version 0.14.1
react-runtime-prod  added, version 0.14.1
tracker             added, version 1.0.9
underscore          added, version 1.0.4

Please log in with your Meteor developer account. If you don't have one, you can quickly create one at www.meteor.com.
Username: markoshust
Password:                                     
=> Errors while publishing build:             

While publishing package build for markoshust:radium:
error: Cannot override existing build
```

and windows:

```
Marks-MacBook-Air:meteor-radium markshust$ meteor admin get-machine os.windows.x86_32

caching-compiler    added, version 1.0.0                              
check               added, version 1.1.0                              
coffeescript        added, version 1.0.11                             
ecmascript          added, version 0.1.6                            
ecmascript-runtime  added, version 0.2.6                              
ejson               added, version 1.0.7      
markoshust:radium   added, version 0.15.3                      
promise             added, version 0.5.1      
random              added, version 1.0.5      
react-runtime-dev   added, version 0.14.1
react-runtime-prod  added, version 0.14.1
tracker             added, version 1.0.9 
underscore          added, version 1.0.4 

Please log in with your Meteor developer account. If you don't have one,
you can quickly create one at www.meteor.com.                           
Username: markoshust                         
Password:                                
=> Errors while publishing build:        

While publishing package build for markoshust:radium:                   
error: Cannot override existing build      
```

Everything seems to work when doing `meteor deploy` now, so this could be a non-issue. However, we can keep an eye on it for future issues and reference this ticket if probs arise.
